### ISSUE TITLE
OrderByDescending have a bug

### ISSUE THREAD

**Issue by yaobo-lab** [joaom182/linqjs#11]
![20190811093428](https://user-images.githubusercontent.com/21329253/62828533-869bb100-bc1b-11e9-83b4-b026057672a1.png)

use a json list OrderByDesc  and print log

**Comment by yozian** [comment]
I face the same issue, the following is what I worked around.

Just specify the comparator of what property to be compared.

``` javascript
var arr = [{Name:"A", Val:1}, {Name:"a", Val:2}, {Name:"B", Val:1}, {Name:"C", Val:2}];

var res = arr.orderByDescending(
    function(t){ return t.Name }, 
    function(a,b){ return linq.SortComparer(a.Val,b.Val); }
);

output:

0: {Name: "a", Val: 2}
1: {Name: "C", Val: 2}
2: {Name: "A", Val: 1}
3: {Name: "B", Val: 1}

```

**Comment by nuclearspike** [comment]
For me, when using orderByDescending, it never calls the first function. My workaround was just to use orderBy(s => s.something).reverse() which is not ideal.

**Comment by joaom182** [comment]
I will check this.

**Comment by georg87** [comment]
Any news on this? I'm still facing this issue.

From what i can tell this should have been fixed by the pull request #7 but it seems that the change was never applied to the distribution files.

Can you please check the distribution files and update the npm repository?

**Comment by joaom182** [comment]
@georg87 i'll release a version to fix this.

**Comment by joaom182** [comment]
@georg87 released.

```
+ linqjs@1.0.2
```
