### ISSUE TITLE
Problem with RemoveAll

### ISSUE THREAD

**Issue by cbfranca** [joaom182/linqjs#4]
Even the Readme example not working.

Follow the error.

Uncaught ReferenceError: Predicate is not defined(…)

**Comment by cbfranca** [comment]
The problem was found in minificated version. Look at "Predicate" instead of "predicate".

**Comment by joaom182** [comment]
@cbfranca I will fix, thanks for report.

**Comment by joaom182** [comment]
@cbfranca resolved with last commit and updated on npm
