### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [joaom182/linqjs#5]
how can i add a comparator in linq? 

i might add ~= ... in the query

**Comment by publicocean0** [comment]
In my code I has a dao where in the methods you pass a predicate instance and the dao executed the query . In a where condition you has a Comparation. Comparator in your code is JavaScript comparator . My predicate can be converted in a query string . I thought to pass this query to linq for executing query .... but my predicates have many possible comparators . Tilde for regular matching or other symbols for matthematcal comparations

**Comment by publicocean0** [comment]
It you be a idea for extended linq but unfortunately I has no time in my project. I realized a light version linq like ... filtering directly the  predicate. I will commit it in the next days .

**Comment by joaom182** [comment]
@publicocean0 Sure! Share the idea! 😃  Lately i also no have time to work here :/

**Comment by joaom182** [comment]
@publicocean0 but.. answering your question, actually you can only provide a "function expression" (high ordered function) to comparers..
