### ISSUE TITLE
Zip returning list of undefined

### ISSUE THREAD

**Issue by mwpowellhtx** [joaom182/linqjs#8]
Is this right?

```JavaScript
[1, 2, 3].zip([4, 5, 6], (x, y) => { x, y });
```

This is yielding:

```
[undefined, undefined, undefined]
```

I don't think that's right?

**Comment by mwpowellhtx** [comment]
Apparently *JavaScript* lambdas are not supported yet, or I do not quite have the parameters correct? With this, it works:

```JavaScript
[1, 2, 3].zip([4, 5, 6], function(x, y) { return { x, y }; });
```

And correctly yields, from *Google Chrome* debugger:

```
(3) [{...}, {...}, {...}]
0: {x:1, y: 4}
1: {x:2, y: 5}
2: {x:3, y: 6}
  length: 3
  __proto__: Array(0)
```

**Comment by joaom182** [comment]
@mwpowellhtx your syntax is wrong on your first example. You're opening statement block `{}`, and not return the value. This is the cause of `undefined`.

The correct syntax with arrow functions is:

`[1, 2, 3].zip([4, 5, 6], (x, y) => ({ x, y }))`;

**Comment by mwpowellhtx** [comment]
Ah, I see... Yes, I am trying to return an object, and I suppose the curly braces are mistaken for a function body. Thanks for clarifying that.
